[deps]
ContinuousWavelets = "96eb917e-2868-4417-9cb6-27e7ff17528f"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Wavelets = "29a6e085-ba6d-5f35-a997-948ac2efa89a"

[compat]
Documenter = "0.25"
